In [13]:
import librosa
import os
import numpy as np
from os import walk
import pickle

In [14]:
def tdataset(point):
    for path, dirs, files in os.walk('Wavfile'):
        files = [f for f in files if not f[0] == '.']
    for name in files:
        y, sr = librosa.load('Wavfile/'+ name, sr=16000, mono=False)
        D = librosa.stft(y[0] + y[1], n_fft = 1024, hop_length = 512)[:,:point]
        D1 = librosa.stft(y[0], n_fft = 1024, hop_length = 512)[:,:point]
        D2 = librosa.stft(y[1], n_fft = 1024, hop_length = 512)[:,:point]
        if D.shape[1] < point:
            tmp = np.zeros((513,point - D.shape[1]),dtype = float)
            D = np.column_stack((D, tmp))
        if D1.shape[1] < point:
            tmp = np.zeros((513,point - D1.shape[1]),dtype = float)
            D1 = np.column_stack((D1, tmp))
        if D2.shape[1] < point:
            tmp = np.zeros((513,point - D2.shape[1]),dtype = float)
            D2 = np.column_stack((D2, tmp))
        magnitude, phase = librosa.magphase(D)
        magnitude = magnitude.T.flatten()
        phase = phase.T.flatten()
        magnitude1, phase1 = librosa.magphase(D1)
        magnitude1 = magnitude1.T.flatten()
        phase1 = phase1.T.flatten()
        magnitude2, phase2 = librosa.magphase(D2)
        magnitude2 = magnitude2.T.flatten()
        phase2 = phase2.T.flatten()
        if name[:3] == 'amy' or name[:7] == 'abjones':
            if name == 'amy_9_08.wav' or name == 'amy_9_09.wav' or name == 'abjones_5_08.wav' or name == 'abjones_5_09.wav':              
                try:
                    dva = np.vstack((dva,magnitude))
                    pva = np.vstack((ptr,phase))
                except UnboundLocalError:
                    dva = magnitude
                    pva = phase
                try:
                    d1va = np.vstack((d1va,magnitude1))
                    p1va = np.vstack((p1va,phase1))
                except UnboundLocalError:
                    d1va = magnitude1
                    p1va = phase1
                try:
                    d2va = np.vstack((d2va,magnitude2))
                    p2va = np.vstack((p2va,phase2))
                except UnboundLocalError:
                    d2va = magnitude2
                    p2va = phase2
            else:
                try:
                    dtr = np.vstack((dtr,magnitude))
                    ptr = np.vstack((ptr,phase))
                except UnboundLocalError:
                    dtr = magnitude
                    ptr = phase
                try:
                    d1tr = np.vstack((d1tr,magnitude1))
                    p1tr = np.vstack((p1tr,phase1))
                except UnboundLocalError:
                    d1tr = magnitude1
                    p1tr = phase1
                try:
                    d2tr = np.vstack((d2tr,magnitude2))
                    p2tr = np.vstack((p2tr,phase2))
                except UnboundLocalError:
                    d2tr = magnitude2
                    p2tr = phase2

        else:
            try:
                dte = np.vstack((dte,magnitude))
                pte = np.vstack((pte,phase))
            except UnboundLocalError:
                dte = magnitude
                pte = phase
            try:
                d1te = np.vstack((d1te,magnitude1))
                p1te = np.vstack((p1te,phase1))
            except UnboundLocalError:
                d1te = magnitude1
                p1te = phase1
            try:
                d2te = np.vstack((d2te,magnitude2))
                p2te = np.vstack((p2te,phase2))
            except UnboundLocalError:
                d2te = magnitude2
                p2te = phase2
    trdata = [dtr,d1tr,d2tr]
    tedata = [dte,d1te,d2te]
    trphase = [ptr, p1tr,p2tr]
    tephase = [pte, p1te,p2te]
    vadata = [dva,d1va,d2va]
    vaphase = [pva,p1va,p2va]
    return trdata ,tedata, trphase, tephase, vadata, vaphase

In [15]:
trdata ,tedata, trphase, tephase, vadata, vaphase = tdataset(100)

In [16]:
pickle.dump( trdata, open( "trdata.p", "wb" ) )
pickle.dump( tedata, open( "tedata.p", "wb" ) )
pickle.dump( trphase, open( "trphase.p", "wb" ) )
pickle.dump( tephase, open( "tephase.p", "wb" ) )
pickle.dump( vadata, open( "vadata.p", "wb" ) )
pickle.dump( vaphase, open( "vaphase.p", "wb" ) )

In [ ]:
from pj_nn import test_DRNN
out = test_DRNN(tedata ,trdata, vadata, learning_rate=0.06, n_epochs=20, batch_size=1, point = 100)

... building the model


In [6]:
tedata[1].shape

(825, 51300)

In [7]:
a = [[2,3,4],[4,5,6]]
b = [1,2,3]
np.vstack((a,b))

array([[2, 3, 4],
       [4, 5, 6],
       [1, 2, 3]])

In [8]:
vadata

[array([[  1.39714193e+00,   1.20462580e-02,   7.23490119e-01, ...,
           4.42754954e-01,   7.59301126e-01,   4.22601312e-01],
        [  2.98981166e+00,   8.62298459e-02,   4.44733948e-01, ...,
           5.14539219e-02,   8.02500267e-03,   1.81616917e-02],
        [  3.51240516e+00,   8.86603177e-01,   3.54337066e-01, ...,
           1.33638131e-02,   6.72096908e-02,   3.34075186e-03]], dtype=float32),
 array([[  1.10531092e+00,   2.54938811e-01,   1.10600516e-01, ...,
           4.42247689e-01,   7.58728623e-01,   4.23738837e-01],
        [  2.95182610e+00,   8.86266232e-02,   4.08591986e-01, ...,
           5.43312132e-02,   5.97698381e-04,   1.77122671e-02],
        [  3.50054312e+00,   8.86082411e-01,   5.18601656e-01, ...,
           9.16802324e-03,   6.84166923e-02,   5.15744695e-03]], dtype=float32),
 array([[  2.91831076e-01,   2.66985059e-01,   8.34090650e-01, ...,
           5.07264980e-04,   5.72485267e-04,   1.13754382e-03],
        [  3.79857160e-02,   2.39677518e-0

In [9]:
pickle.load("vadata.p")

AttributeError: 'str' object has no attribute 'readline'

In [10]:
vadata = pickle.load( open( "vadata.p", "rb" ) )

In [11]:
len(vadata)

3

In [12]:
vadata[2].shape

(3, 51300)